version: '3'

services:
    # Databases
    product-db:
        image: postgres:15
        environment:
            POSTGRES_DB: product_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - product_data:/var/lib/postgresql/data
        ports:
            - '9432:5432'

    customer-db:
        image: postgres:15
        environment:
            POSTGRES_DB: customer_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - customer_data:/var/lib/postgresql/data
        ports:
            - '9433:5432'

    order-db:
        image: postgres:15
        environment:
            POSTGRES_DB: order_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - order_data:/var/lib/postgresql/data
        ports:
            - '9434:5432'

    # Message Broker
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - '9672:5672'
            - '19672:15672'
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest

    # Services
    product-service:
        build: ./product-service
        ports:
            - '3001:3001'
        depends_on:
            - product-db
            - rabbitmq
        environment:
            - DB_HOST=product-db
            - DB_PORT=5432
            - DB_NAME=product_db
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - PORT=3001
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

    order-service:
        build: ./order-service
        ports:
            - '3002:3002'
        depends_on:
            - order-db
            - product-service
            - rabbitmq
        environment:
            - DB_HOST=order-db
            - DB_PORT=5432
            - DB_NAME=order_db
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - PORT=3002
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
            - PRODUCT_SERVICE_URL=http://product-service:3001

    customer-service:
        build: ./customer-service
        ports:
            - '3003:3003'
        depends_on:
            - customer-db
            - rabbitmq
        environment:
            - DB_HOST=customer-db
            - DB_PORT=5432
            - DB_NAME=customer_db
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - PORT=3003
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

    api-gateway:
        build: ./api-gateway
        ports:
            - '3000:3000'
        depends_on:
            - product-service
            - order-service
        environment:
            - PORT=3000
            - PRODUCT_SERVICE_URL=http://product-service:3001
            - ORDER_SERVICE_URL=http://order-service:3002
            - JWT_SECRET=your_jwt_secret_key_here

    inventory-db:
        image: postgres:15
        environment:
            POSTGRES_DB: inventory_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - inventory_data:/var/lib/postgresql/data
        ports:
            - '9435:5432'

    inventory-service:
        build: ./inventory-service
        ports:
            - '3004:3004'
        depends_on:
            - inventory-db
            - rabbitmq
            - product-service
        environment:
            - DB_HOST=inventory-db
            - DB_PORT=5432
            - DB_NAME=inventory_db
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - PORT=3004
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
            - PRODUCT_SERVICE_URL=http://product-service:3001

volumes:
    product_data:
    customer_data:
    order_data:
    inventory_data:
